### ISSUE TITLE
Support Cerebral 1.0

### ISSUE THREAD

**Issue by garth** [jeroenverfallie/atom-cerebral-signal-bootstrap#2]
Now that Cerebral has hit 1.0 with a stable API, it would be great to support the current idiomatic cerebral approach as well as the rename from addons to operators.

**Comment by jeroenverfallie** [comment]
@garth I'll get to this tonight, thanks for reminding me!

**Comment by garth** [comment]
No rush, I was just pruning my atom plugins and wondered about the future of this one.

**Comment by jeroenverfallie** [comment]
Locally, I now have a new version ready, with more configuration options.

I now match the same things as before + `addSignals` & the `chain` property on it.
For legacy reasons, I still support signal files, however, by default, everything will be a chain.

The same style options are available, I felt they are at a sweet spot and don't require more effort for now. I'm always open for suggestions though.

![options](https://cloud.githubusercontent.com/assets/1143308/17752321/86b86d9a-64cb-11e6-814e-485a32a2ed62.png)

Additionally, I now added template options, so you can play with them, customize them, etc.
These use special keys which are replaced with the generated content. I'll document them later.

![settings](https://cloud.githubusercontent.com/assets/1143308/17752365/bee1f27c-64cb-11e6-95c9-af9c0e2dfab3.png)

Lastly, because atom couldn't handle arrays of objects, I went with JSON for the extra options.
These are my favorite, because they allow you to fix some reusable actions/factories/.. faster.

``` JSON
{
    "specialImports": [
        {
            "keys": ["debounce", "set", "unset", "when", "throttle", "toggle", "copy"],
            "importPath": "cerebral/operators/_KEY_"
        }
    ]
}
```

---

Now, I haven't yet released this version, because I'm unsure these settings work in their scope, the editor.

The plugin is written (more so now) in a way  parsing/generating can be decoupled from the actual editor interaction. In other words, the same parse & generator code could be used in other editors, command line tools, ...

So the atom specific part is just the config, keybinds, triggers & file api.

On that note, I feel like these settings are a convention in your project, and should apply to any collaborator. 

So.... this feels like a `.rc` file??
Perhaps this could be a generic config which works for `cerebral-cli` too. 
In which this plugin functionality could even be added, for vim/terminal junkies.

`cerebral make:imports file.js` (idk)

What do you think? @garth @christianalfoni @bfitch

**Comment by garth** [comment]
Looks good to me, the only question I have is: Would it be possible to grab the spacing preference from atom or editor config?

For example, my personal preference is for 2 spaces but I also do some freelance work where the customer prefers 4. So I use an .editorconfig for each project and may switch between projects several times a day.

Also same thing for semicolons, but I guess that would be harder to figure out?

[just re-read your last comment, I guess that an rc file might fix my issues?]

**Comment by christianalfoni** [comment]
This is completely awesome! 👍 😄  I suggest we just create an `.rc` file now and then see how it can/should be incorporated with other tools? :)

**Comment by bfitch** [comment]
Yeah @jeroenverfallie! This is awesome! It would be really cool to piggyback off this to provide some generators in `cerebral-cli` (if it's not too much work 😛 ).

**Comment by jeroenverfallie** [comment]
Thanks for the feedback, I'll get to this tonight 🎊

**Comment by jeroenverfallie** [comment]
@bfitch It's not a lot of work, as I now test the whole core through cli anyway 💃 
@garth Indeed, the rc file fixes semi-colons, and I added an option for `editorconfig` to determine the whitespace.
@christianalfoni 

---

The editor plugin will have an extra option `useRcFile`, if enabled, it will search recursively up for a `.cerebralrc` file (and lastly if not found in your homedir much like any other .rc files), and extend the defaultConfig with it, if found.
if not enabled, it'll just work with the editor settings as shown above (but slightly refactored)

---

The .rc file can be in either json or cson format, the node package `season` is used to parse it.
Here's the config I came up with, in both formats. (I like cson for multiline text, for the templates)

https://gist.github.com/jeroenverfallie/57d77602910e7817b1200dd5732a7c96

Some info:
- if you set (in `paths`) both `chainFactories` and `actionFactories` to use the same path, there's no differentiation, so it's configurable as you please.
- templates use some variables which are replaced with the appropriate content. They should be quite clear, only some whitespace issues once in a while 😄 
- specialImports can be either a collection of keys all mapping to an equal format with the `{KEY}` being replaced, or they can be a simple 1 to 1 map.
- specialImports can be overwritten, the last defined mapping is what is being used.

---

I'd like to place the core functionality in a package, I was thinking.. `cerebral-cli-generator`.. but @bfitch maybe you can help here with the naming convention.

The usage is as simple as:

``` js
var cerebralCliGenerator = require('cerebral-cli-generator');

const newFileContent = cerebralCliGenerator.performOnFile({
    filePath: path.join(__dirname, 'chains', 'abc.js'),
    config: null,
    write: true
});
```

The `write` option is for editor vs cli. If true, it'll write the new text (imports added to your original file). If false, you have to do this yourself, for example in atom `editor.setText(newFileContent)`

---

So lovely when it works on complex things like christianalfoni's discord example :) https://gist.github.com/jeroenverfallie/ad76dd683d775f588fb87e0445f6752e
🎊 🎊 🎊

**Comment by christianalfoni** [comment]
Hahaha, this is just amazing work @jeroenverfallie , I am super impressed!!! 👍 😄

**Comment by jeroenverfallie** [comment]
Woop.

It's live, your atom should be receiving the update soonish.
The new package is located (for now) here: https://github.com/jeroenverfallie/cerebral-cli-generator

Enjoy the weekend!

(Make sure you have 1.0.2)
